trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Installing dependencies..."
  displayName: Install

- script: echo "Building application..."
  displayName: Build

- script: |
    echo "Navigating to correct folder..."
    cd 04-Projects/01-project-basic-CI-Pipeline
    echo "Running our real application code..."
    node sample-app/app.js
  displayName: Run App

- script: echo "Running tests..."
  displayName: Test