trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # 1. Tumhara Service Connection Naam
  azureServiceConnection: 'my-svc-srk'
  
  # 2. Tumhara Web App Naam
  webAppName: 'sharik-dream-app'

steps:
# Step 1: Website files ko ZIP package mein band karna (P Capital Kiya)
- task: ArchiveFiles@2
  displayName: 'Package Website Files'
  inputs:
    # 💡 Yahan humne '04-Projects' ka P capital kar diya hai
    rootFolderOrFile: '$(Build.SourcesDirectory)/04-Projects/project-02-webapp-deployment/app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/website.zip'
    replaceExistingArchive: true

# Step 2: ZIP package ko direct Azure Web App par deploy karna
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(webAppName)'
    appType: 'webAppLinux' 
    package: '$(Build.ArtifactStagingDirectory)/website.zip'